---
- name: Enable Windows Service 
  win_service:
    name: "{{ item.name }}"
    start_mode: auto
    state: started 
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ target_services }}"
  tags:
    - enable_service 
...
