---
# This is the Chocolatey Role to install and config Windows packages

# Installing package
- name: Install Chocolatey packages
  win_chocolatey:
    name: "{{ item.name }}"
    params: "{{ item.param }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ target_packages }}"
  tags:
    - install_package
...
