---
- name: Create Domain Users 
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    email: "{{ item.email }}"
    state: present
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ target_users }}"
  tags:
    - create_user
...
